import { useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, BadgeCheck, BellRing, BrainCircuit, Building2, ChevronDown, CircleUserRound, HeartPulse, LockKeyhole, Radio, ShieldCheck, Stethoscope, UsersRound, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';

const roles = [
  { title:'Patient', copy:'Monitor your health and stay connected.', to:'/patient/login', icon:CircleUserRound },
  { title:'Doctor', copy:'Review authorized monitoring and AI-assisted insights.', to:'/doctor/login', icon:Stethoscope },
  { title:'Guardian', copy:"Stay informed about your loved one's safety.", to:'/guardian/login', icon:UsersRound },
  { title:'Volunteer', copy:'Respond to verified community emergencies.', to:'/volunteer/login', icon:HeartPulse },
  { title:'College', copy:'Verify students and recognize community contribution.', to:'/college/login', icon:Building2 },
];
const features = [
  ['AI emergency detection','Fall, inactivity, and unusual-pattern signals are evaluated together.', BrainCircuit],
  ['Predictive risk trends','Personal baseline changes support timely, human review.', Activity],
  ['Privacy-preserving sensing','Role-based access and minimum necessary sharing guide every view.', LockKeyhole],
  ['Human response network','Doctors, guardians, and verified responders receive coordinated alerts.', BellRing],
  ['Verified community care','College-backed verification supports safer volunteer participation.', BadgeCheck],
  ['Care Credits','Verified contribution becomes an auditable recognition record.', HeartPulse],
];
const steps = ['Sense','Understand','Predict','Verify','Alert','Respond','Learn'];

export default function Landing(){
  const [chooser,setChooser]=useState(false);
  return <div className="min-h-screen bg-slate-950 text-slate-100 selection:bg-indigo-500/40">
    <header className="sticky top-0 z-50 border-b border-slate-800/80 bg-slate-950/90 backdrop-blur-xl">
      <nav className="mx-auto max-w-7xl h-16 px-5 flex items-center justify-between">
        <a href="#home" className="flex gap-2 items-center font-black tracking-tight"><span className="grid place-items-center h-8 w-8 rounded-xl bg-indigo-600"><HeartPulse className="w-4 h-4"/></span>AIoT Care</a>
        <div className="hidden md:flex gap-6 text-xs text-slate-400"><a href="#how" className="hover:text-white">How it works</a><a href="#features" className="hover:text-white">Features</a><a href="#privacy" className="hover:text-white">AI & privacy</a><a href="#community" className="hover:text-white">Community care</a><a href="#impact" className="hover:text-white">Impact</a></div>
        <div className="flex gap-2"><button onClick={()=>setChooser(true)} className="px-3 py-2 text-xs font-semibold text-slate-300">Sign in</button><a href="#roles" className="px-3 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-xs font-bold">Get started</a></div>
      </nav>
    </header>
    <main id="home">
      <section className="relative overflow-hidden border-b border-slate-900"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_35%,rgba(79,70,229,.22),transparent_30%),radial-gradient(circle_at_20%_10%,rgba(14,165,233,.11),transparent_25%)]"/><div className="relative mx-auto max-w-7xl px-5 pt-20 pb-24 grid lg:grid-cols-2 gap-14 items-center"><div><p className="inline-flex gap-2 items-center text-[10px] font-bold uppercase tracking-[.18em] text-indigo-300"><span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse"/>Privacy-preserving emergency support</p><h1 className="mt-5 text-4xl sm:text-6xl font-black tracking-tight leading-[1.03]">When every second matters,<br/><span className="text-indigo-300">intelligence detects.</span><br/>People respond.</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-400">AI-powered health monitoring that brings together wearable IoT, privacy-aware sensing, predictive risk analysis, and a verified community response network.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#roles" className="px-5 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 font-bold text-sm">Get started <ArrowRight className="inline w-4 h-4 ml-1"/></a><a href="#how" className="px-5 py-3 rounded-xl border border-slate-700 hover:border-slate-500 font-bold text-sm">Explore how it works</a></div><p className="mt-6 text-xs text-slate-500">Designed for responsible healthcare innovation.</p></div>
      <div className="relative"><div className="rounded-[2rem] border border-indigo-400/20 bg-slate-900/80 shadow-2xl p-5 sm:p-7"><div className="flex justify-between items-center"><p className="text-xs font-bold">Live safety signal</p><span className="text-[10px] text-emerald-400">● Secure IoT sync</span></div><div className="mt-7 grid grid-cols-3 gap-3 text-center"><Node icon={<Radio/>} label="Wearable"/><Node icon={<BrainCircuit/>} label="AI risk engine" active/><Node icon={<BellRing/>} label="Response"/></div><div className="relative h-24 my-3"><div className="absolute left-[16%] right-[16%] top-1/2 h-px bg-gradient-to-r from-indigo-500 via-sky-400 to-emerald-400"/><div className="absolute left-[31%] top-[36%] h-4 w-4 rounded-full bg-sky-400 animate-ping"/><div className="absolute right-[31%] top-[36%] h-4 w-4 rounded-full bg-emerald-400 animate-pulse"/></div><div className="grid grid-cols-3 gap-3"><Metric label="Current risk" value="18" note="Low"/><Metric label="Forecast" value="24" note="30 min"/><Metric label="Response" value="Ready" note="Human network"/></div><div className="mt-5 p-4 rounded-2xl bg-slate-950 border border-slate-800 flex gap-3"><ShieldCheck className="w-5 h-5 text-emerald-400 shrink-0"/><p className="text-xs text-slate-400">Multi-sensor evidence is evaluated before an alert is escalated.</p></div></div></div></div></section>
      <section className="border-b border-slate-900 bg-slate-900/40"><div className="mx-auto max-w-7xl px-5 py-5 flex flex-wrap justify-center gap-x-8 gap-y-3 text-xs text-slate-400"><span>🔒 Privacy first</span><span>🤖 AI-assisted</span><span>📡 IoT connected</span><span>🧑‍⚕️ Human response</span><span>🎓 Verified volunteers</span></div></section>
      <section id="roles" className="mx-auto max-w-7xl px-5 py-20"><p className="text-indigo-300 text-xs font-bold uppercase tracking-widest">One platform, five perspectives</p><h2 className="mt-3 text-3xl font-black">Who are you?</h2><p className="mt-3 text-slate-400 max-w-2xl">Choose the workspace designed for your role in safer, connected care.</p><div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-5 gap-4">{roles.map(r=><Link to={r.to} key={r.title} className="group p-5 rounded-3xl border border-slate-800 bg-slate-900 hover:-translate-y-1 hover:border-indigo-500 transition"><r.icon className="w-6 h-6 text-indigo-300"/><h3 className="mt-5 font-bold">{r.title}</h3><p className="mt-2 min-h-10 text-xs leading-5 text-slate-400">{r.copy}</p><span className="mt-5 inline-block text-xs font-bold text-indigo-300">Open portal <ArrowRight className="inline w-3.5 h-3.5"/></span></Link>)}</div></section>
      <section className="bg-slate-900/50 py-20"><div className="mx-auto max-w-5xl px-5 text-center"><p className="text-rose-300 text-xs font-bold uppercase tracking-widest">The care gap</p><h2 className="mt-3 text-3xl font-black">Emergencies don’t always announce themselves.</h2><p className="mt-5 text-slate-400 leading-7">Falls, unusual inactivity, and changing patterns can happen when people are alone. Detection alone is not enough—someone still needs to respond.</p><div className="mt-10 grid sm:grid-cols-4 gap-3"><Flow label="Detection"/><Flow label="Alert"/><Flow label="Who responds?" warn/><Flow label="Coordinated care" good/></div></div></section>
      <section id="how" className="mx-auto max-w-7xl px-5 py-20"><p className="text-indigo-300 text-xs font-bold uppercase tracking-widest">From detection to response</p><h2 className="mt-3 text-3xl font-black">A clear safety workflow.</h2><div className="mt-10 grid grid-cols-2 md:grid-cols-4 xl:grid-cols-7 gap-3">{steps.map((s,i)=><div key={s} className="relative rounded-2xl p-4 bg-slate-900 border border-slate-800"><span className="text-[10px] text-indigo-300">0{i+1}</span><p className="font-bold mt-3">{s}</p><p className="mt-2 text-[10px] text-slate-500">{['Wearable + IoT','Signals interpreted','Baseline forecasting','Evidence + response','Care network notified','Verified assistance','History + learning'][i]}</p></div>)}</div></section>
      <section id="features" className="bg-slate-900/50 py-20"><div className="mx-auto max-w-7xl px-5"><p className="text-indigo-300 text-xs font-bold uppercase tracking-widest">Protection in layers</p><h2 className="mt-3 text-3xl font-black">One platform. Multiple layers of protection.</h2><div className="mt-9 grid md:grid-cols-2 lg:grid-cols-3 gap-4">{features.map(([title,copy,Icon]:any)=><article key={title} className="p-6 rounded-3xl border border-slate-800 bg-slate-950"><Icon className="text-indigo-300 w-6 h-6"/><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{copy}</p></article>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 grid lg:grid-cols-2 gap-10 items-center"><div><p className="text-indigo-300 text-xs font-bold uppercase tracking-widest">Predictive intelligence</p><h2 className="mt-3 text-3xl font-black">Don’t just detect the event. Understand the trend.</h2><p className="mt-5 text-slate-400 leading-7">Risk is estimated from changes in personal baseline and multimodal signals. Forecasts support decisions; they are not medical diagnoses.</p></div><div className="p-6 bg-slate-900 rounded-3xl border border-slate-800"><div className="flex justify-between"><span className="text-xs text-slate-400">Risk trend · simulated demo</span><span className="text-amber-300 font-bold">42 → 73</span></div><div className="h-40 mt-5 flex items-end gap-3">{[42,48,61,73].map((n,i)=><div key={n} className="flex-1"><div style={{height:`${n}%`}} className="rounded-t-xl bg-gradient-to-t from-indigo-600 to-sky-400"/><p className="mt-2 text-center text-[10px] text-slate-500">{['Now','15 min','30 min','60 min'][i]}</p><p className="text-center text-xs font-bold">{n}</p></div>)}</div></div></section>
      <section id="privacy" className="bg-indigo-950/30 border-y border-indigo-900/40 py-20"><div className="mx-auto max-w-6xl px-5"><p className="text-indigo-200 text-xs font-bold uppercase tracking-widest">Privacy architecture</p><h2 className="mt-3 text-3xl font-black">Healthcare intelligence without unnecessary exposure.</h2><div className="mt-9 grid md:grid-cols-5 gap-3 text-center">{['Raw sensor data','Edge processing','Relevant features','Secure backend','Role-based access'].map((x,i)=><div key={x} className="p-4 rounded-2xl bg-slate-950/70 border border-indigo-900/50"><p className="text-[10px] text-indigo-300">0{i+1}</p><p className="mt-2 text-sm font-bold">{x}</p></div>)}</div><p className="mt-6 text-sm text-slate-400">Each role sees only what is authorized: volunteers receive minimum response information, while institutions manage verification and contribution—not patient records.</p></div></section>
      <section id="community" className="mx-auto max-w-7xl px-5 py-20"><div className="grid lg:grid-cols-2 gap-10"><div><p className="text-emerald-300 text-xs font-bold uppercase tracking-widest">Community care network</p><h2 className="mt-3 text-3xl font-black">Technology detects. Community responds.</h2><p className="mt-5 text-slate-400 leading-7">AIoT provides a safety signal; trusted people coordinate meaningful support. Verified volunteers are matched only for eligible events and operate with minimal necessary information.</p><div className="mt-7 flex flex-wrap gap-2">{['Patient','AI detects','Doctor + Guardian','Verified volunteer','Assistance','Care Credits'].map(x=><span key={x} className="text-xs p-2.5 rounded-xl bg-slate-900 border border-slate-800">{x}</span>)}</div></div><div className="p-6 bg-slate-900 rounded-3xl border border-slate-800"><h3 className="font-bold">Care Credits · simulated example</h3><div className="mt-6 grid grid-cols-2 gap-3">{[['12','missions'],['24','community hours'],['642','Care Credits'],['1','verified certificate']].map(([n,l])=><Metric key={l} label={l} value={n} note=""/>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">Care Credits recognize verified community contribution. Recognition and reward options are configurable through responsible institutional partnerships.</p></div></div></section>
      <section id="impact" className="bg-slate-900/50 py-20"><div className="mx-auto max-w-7xl px-5 text-center"><p className="text-indigo-300 text-xs font-bold uppercase tracking-widest">Demo metrics</p><h2 className="mt-3 text-3xl font-black">Built for people, not just data.</h2><div className="mt-9 grid grid-cols-2 lg:grid-cols-5 gap-3">{[['5','connected roles'],['312','verified volunteers'],['2,840','community hours'],['624','response missions'],['18,420','Care Credits']].map(([n,l])=><Metric key={l} value={n} label={l} note="simulated platform metric"/>)}</div></div></section>
      <section className="mx-auto max-w-5xl px-5 py-24 text-center"><p className="text-indigo-300 text-xs font-bold uppercase tracking-widest">AI assists. Humans decide.</p><h2 className="mt-4 text-4xl font-black">Be part of a safer care network.</h2><p className="mt-5 text-slate-400">Technology detects. People respond. Together, we care.</p><div className="mt-8 flex flex-wrap justify-center gap-3">{roles.map(r=><Link to={r.to} key={r.title} className="px-4 py-2.5 rounded-xl bg-slate-900 border border-slate-700 hover:border-indigo-500 text-sm">I’m a {r.title}</Link>)}</div></section>
    </main>
    <footer className="border-t border-slate-800 px-5 py-10"><div className="mx-auto max-w-7xl flex flex-col md:flex-row gap-5 justify-between"><div><b>AIoT Care</b><p className="mt-2 text-xs text-slate-500">Intelligent detection. Human response.</p></div><p className="max-w-2xl text-[10px] leading-5 text-slate-600">© 2026 AIoT Care. This platform is a prototype for AI-assisted health monitoring and emergency-response support. It is not a replacement for professional medical care or emergency services.</p></div></footer>
    {chooser&&<div className="fixed inset-0 z-[60] bg-slate-950/80 backdrop-blur-sm p-5 grid place-items-center"><div role="dialog" aria-modal="true" className="w-full max-w-2xl bg-slate-900 border border-slate-700 rounded-3xl p-6"><div className="flex justify-between"><div><h2 className="font-black">Choose your portal</h2><p className="text-xs text-slate-400 mt-1">Select the role you use today.</p></div><button onClick={()=>setChooser(false)} aria-label="Close" className="text-slate-400 text-xl">×</button></div><div className="mt-5 grid sm:grid-cols-2 gap-3">{roles.map(r=><Link onClick={()=>setChooser(false)} to={r.to} key={r.title} className="p-4 rounded-2xl border border-slate-800 hover:border-indigo-500"><r.icon className="w-5 h-5 text-indigo-300"/><p className="font-bold mt-3">{r.title}</p><p className="mt-1 text-xs text-slate-400">{r.copy}</p></Link>)}</div></div></div>}
  </div>
}
function Node({icon,label,active=false}:{icon:any,label:string,active?:boolean}){return <div className={`p-4 rounded-2xl border ${active?'border-sky-400/60 bg-sky-950/30':'border-slate-700 bg-slate-950'}`}><div className="mx-auto grid place-items-center w-9 h-9 rounded-xl bg-slate-800 text-indigo-300">{icon}</div><p className="mt-2 text-[10px] font-bold">{label}</p></div>}
function Metric({label,value,note}:{label:string,value:string,note:string}){return <div className="p-4 rounded-2xl bg-slate-950 border border-slate-800"><p className="text-2xl font-black">{value}</p><p className="mt-1 text-[10px] uppercase text-slate-400">{label}</p>{note&&<p className="mt-1 text-[9px] text-slate-600">{note}</p>}</div>}
function Flow({label,warn=false,good=false}:{label:string,warn?:boolean,good?:boolean}){return <div className={`rounded-2xl border p-4 text-sm font-bold ${warn?'border-amber-800 bg-amber-950/20 text-amber-200':good?'border-emerald-800 bg-emerald-950/20 text-emerald-200':'border-slate-800 bg-slate-950'}`}>{label}</div>}
